# Generated by Django 3.1.1 on 2020-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_type', models.CharField(blank=True, choices=[('inhouse', 'In house'), ('outsourced', 'Outsourced')], max_length=40, null=True)),
                ('hour', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/driver/')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=40, null=True)),
            ],
        ),
    ]
