# Generated by Django 3.1.1 on 2020-10-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_type',
        ),
    ]
