# Generated by Django 3.1.1 on 2020-10-29 19:14

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20201001_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django.contrib.postgres.fields.hstore.HStoreField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
