# Generated by Django 3.1.1 on 2020-10-31 12:19

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driverattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverattendance',
            name='date',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
