# Generated by Django 3.1.1 on 2020-11-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20201105_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='hour',
        ),
    ]
