# Generated by Django 3.1.1 on 2020-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driver_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='employee_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
