# Generated by Django 3.1.1 on 2020-12-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20201129_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='employee_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
