# Generated by Django 3.1.1 on 2020-09-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('stack', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('project', '0002_auto_20200915_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_type', models.CharField(blank=True, choices=[('04x03m', '04x03 M')], max_length=40, null=True)),
                ('payload', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('panel_number', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('returned', 'Returned'), ('diployed', 'Diployed'), ('ready-to-collect', 'Ready to cllect')], max_length=40, null=True)),
                ('stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stack.stack')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('approx_time', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('stack', models.ManyToManyField(to='dispatch.DispatchStack')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
