# Generated by Django 3.1.1 on 2020-09-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchstack',
            name='stack_type',
        ),
    ]
