# Generated by Django 3.1.1 on 2020-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_remove_dispatchstack_stack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='approx_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
