# Generated by Django 3.1.1 on 2020-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_auto_20200917_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchStackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
            ],
        ),
    ]
