# Generated by Django 3.1.1 on 2020-09-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_dispatchstackstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DispatchStackStatus',
        ),
        migrations.AlterField(
            model_name='dispatchstack',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.stackstatus'),
        ),
    ]
