# Generated by Django 3.1.1 on 2020-10-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_auto_20201001_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='status',
        ),
        migrations.DeleteModel(
            name='DispatchStatus',
        ),
    ]
