# Generated by Django 3.1.1 on 2020-10-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_auto_20201001_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=40, null=True),
        ),
    ]
