# Generated by Django 3.1.1 on 2020-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_dispatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=40),
        ),
    ]
