# Generated by Django 3.1.1 on 2020-10-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_auto_20201002_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='date',
        ),
    ]
