# Generated by Django 3.1.1 on 2020-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_remove_dispatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
