# Generated by Django 3.1.1 on 2020-11-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_dispatch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='status',
        ),
    ]
