# Generated by Django 3.1.1 on 2020-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_dispatch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
