# Generated by Django 3.1.1 on 2020-11-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0016_auto_20201105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='optional_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delay_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.delayreason'),
        ),
    ]
