# Generated by Django 3.1.1 on 2020-11-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0017_auto_20201105_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchstatus',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
