# Generated by Django 3.1.1 on 2020-09-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_role',
            field=models.CharField(blank=True, choices=[('dispatch-coordinator', 'Dispatch coordinator'), ('admin', 'Admin')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired')], max_length=40, null=True),
        ),
    ]
