# Generated by Django 3.1.1 on 2020-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201014_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
