# Generated by Django 3.1.1 on 2020-09-30 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20200930_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
