# Generated by Django 3.1.1 on 2020-09-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicletype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
