# Generated by Django 3.1.1 on 2020-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20201105_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
