# Generated by Django 3.1.1 on 2020-11-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_vehicletype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
