# Generated by Django 3.1.1 on 2020-11-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20201105_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='travel_time',
        ),
    ]
