# Generated by Django 3.1.1 on 2020-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
