# Generated by Django 3.1.1 on 2020-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('stack_type', models.CharField(blank=True, choices=[('04x03m', '04x03 M')], max_length=40, null=True)),
                ('stack_number', models.CharField(blank=True, max_length=80, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/vehicle/')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=40, null=True)),
            ],
        ),
    ]
