# Generated by Django 3.1.1 on 2020-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/stack/'),
        ),
    ]
