# Generated by Django 3.1.1 on 2020-10-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_auto_20200916_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='stack_type',
        ),
    ]
