# Generated by Django 3.1.1 on 2020-10-01 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack', '0003_remove_stack_stack_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stack',
            name='stack_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stack.stacktype'),
        ),
    ]
