# Generated by Django 3.1.1 on 2020-11-05 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0005_auto_20201105_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
