# Generated by Django 3.1.1 on 2020-11-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0006_auto_20201105_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='stacktype',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
